### PR TITLE
Fix #40 and Fix #32

### LINKED ISSUE #32: Proper error logging must be done when ports used in HTTP configurations are already in use
**Description:**
If the port we have used to make the HTTP(S) connection is already being used by a different program in the server, an error must be thrown. However, no such error is displayed on the console as of now. The only observation is, the connection messages such as 'Source Listener has created for url http://localhost:5005/inputStream' would not be displayed when the Siddhi application containing the relevant HTTP source configuration is run.

**Steps to reproduce:**
Consider the following HTTP source configuration (Here, 8005 is assumed to be a port already being used by a different program in the system). Add this configuration to a siddhi app, save it and run on the editor environment (or as worker) in WSO2 Stream Processor. You would notice that no connection messages are displayed on the console. However, no errors are displayed either. When attempting to publish data only, the user would know that the HTTP connection is not established.

@Source(type = 'http', receiver.url='http://localhost:8005/inputStream',  basic.auth.enabled='false',
@map(type='text'))
define stream inputStream(name string, age int, country string);

This issue must be resolved by logging proper error messages, when the port used in HTTP source configuration is already used by a different program.

### LINKED ISSUE #40: Incorrect testcase naming format.
**Description:**
Incorrect test case naming format which cause to skip test at building.

**Suggested Labels:**
Bug

**Suggested Assignees:**
@Yasara123

### PR DESCRIPTION
**Pull request by Yasara123**

### CODE REVIEW

File: component/src/main/java/org/wso2/extension/siddhi/io/http/source/HttpAuthenticator.java [hunk 1]
```diff
@@ -70,11 +70,12 @@ public static boolean authenticate(HTTPCarbonMessage httpCarbonMessage) {
                             return false;
                         }
                     } catch (IdPClientException e) {
-                        logger.error("Authorization fails.");
+                        logger.error("Authorization process fails for " + usernamePassword[0] + ":" +
```
Comment (sajithshn) [inline component/src/main/java/org/wso2/extension/siddhi/io/http/source/HttpAuthenticator.java]: I thin you shouldn't log the password when faling

Comment (Yasara123) [reply component/src/main/java/org/wso2/extension/siddhi/io/http/source/HttpAuthenticator.java]: Fixed in 6bf095af9d7a4c00220069badb50517cec553139
